#!/bin/bash

###
# node install script for Alpine Linux on Docker
###
runNode () {
    local DIVIDER="===================="
    local TEMPLATE="\n\n${DIVIDER}${DIVIDER}${DIVIDER}\n%s\n\n\n"

    ###
    # NOTE: additional packages for possible Node.js dependencies compile
    ###
    printf "${TEMPLATE}" "Installing Alpine Linux Packages for Node.js"
    apk update && apk add \
        autoconf \
        automake \
        binutils-gold \
        curl \
        g++ \
        gcc \
        gnupg \
        libgcc \
        libpng-dev \
        libstdc++ \
        libtool \
        libuv-dev \
        linux-headers \
        make \
        nasm \
        openssl-dev \
        paxctl \
        python \
        tar \
        zlib-dev
}

runNode && exit 0
