#!/bin/bash

###
# node install script for Alpine Linux on Docker
###
runNode () {
    local DIVIDER="===================="
    local TEMPLATE="\n\n${DIVIDER}${DIVIDER}${DIVIDER}\n%s\n\n\n"

    ###
    # NOTE: add additional file/folder removal here for all images
    ###
    printf "${TEMPLATE}" "Removing Alpine Linux Packages for Node.js"
    clearNodeInstallCache
}

###
# cleanup after node install
# TODO: allow for subset to be passed for deletion
###
clearNodeInstallCache () {
    ###
    # NOTE: remove required packages for node/npm download and compile
    ###
    apk del \
        autoconf \
        automake \
        binutils-gold \
        curl \
        g++ \
        gcc \
        gnupg \
        libpng-dev \
        libtool \
        libuv-dev \
        linux-headers \
        make \
        nasm \
        openssl-dev \
        paxctl \
        python \
        tar \
        zlib-dev
}

runNode && exit 0
