#!/usr/bin/env bash

###
# project install script for project dependencies
#   - this can and should be run as needed in dev environment to update project dependencies
#       - example: re-running "npm install" to update versions
###
runProject () {
    local DIVIDER="===================="
    local TEMPLATE="\n\n${DIVIDER}${DIVIDER}${DIVIDER}\n%s\n\n\n"

    if [[ "${NODE_ENV}" == "production" ]]; then
        printf "${TEMPLATE}" "Installing (Production) Node.js Dependencies"
        npm install --quiet --no-optional --production
    else

        if [[ -f ./package.json ]]; then
            # NOTE: add any packages required for node dependencies
            # e.g. apk update && add tar

            # NOTE: add any node global dependencies
            # printf "${TEMPLATE}" "Installing (Global) Node Dependencies"
            # e.g. npm install --quiet -g gulp-cli

            printf "${TEMPLATE}" "Installing (All) Node.js Dependencies"
            npm install --quiet --no-optional
        fi

        if [[ -f ./bower.json ]]
        then
            printf "${TEMPLATE}" "Installing Bower Dependencies"
            npm install --quiet -g bower
            bower install --allow-root
        fi

    fi

    ###
    # NOTE: remove any additional project-specific files/folders
    ###
    printf "${TEMPLATE}" "Clearing Node and NPM cache"
    rm -rf \
        ${HOME_DIR}/.npm \
        ${HOME_DIR}/.node-gyp
}

runProject
