#!/bin/bash

###
# base environment install script for Alpine Linux on Docker
###
runBase () {
    local DIVIDER="===================="
    local TEMPLATE="\n\n${DIVIDER}${DIVIDER}${DIVIDER}\n%s\n\n\n"

    ###
    # NOTE: packages for env improvements are a personal preference here...
    #   - bash-completion coreutils grep tree
    ###
    printf "${TEMPLATE}" "Installing Alpine Linux Packages for Base"
    apk add \
        coreutils \
        grep \
        tree

    ###
    # NOTE: check if DEV_ENV, DEV_UID, and DEV_USER are defined to setup dev user
    ###
    if [[ "${DEV_ENV}" == "linux" && -n "${DEV_UID}" && -n "${DEV_USER}" ]]; then
        adduser -u ${DEV_UID} -D ${DEV_USER}
    fi
}

runBase && exit 0
